---

root_dir: "{{ GISLAB_PATH_SYSTEM }}/clients/desktop"
root_dir_cluster: "{{ GISLAB_PATH_SYSTEM }}/cluster"


# get list of Ubuntu installer tasks: $ tasksel --list-tasks
# get list of packages included in task: $ tasksel --task-packages <task>

packages_kernel:
  # list of Linux kernel packages (installed without recommended packages)
  - linux-image-generic
  - linux-headers-generic


packages_virtualbox:
  # list of VirtualBox packages (installed without recommended packages)
  - virtualbox-guest-utils
  - virtualbox-guest-dkms
  - virtualbox-guest-x11


packages_base:
  # list of basic server packages (installed with recommended packages)
  - acpid
  - apt-show-versions
  - bc
  - busybox-initramfs
  - busybox-static
  - curl
  - genisoimage
  - initramfs-tools
  - libnss-ldap
  - libpam-pwquality
  - libsasl2-modules
  - munin-node
  - nbd-client
  - nfs-common
  - openssh-server
  - pxelinux
  - rsyslog
  - serf
  - software-properties-common
  - syslinux-common
  - udhcpc
  - unzip
  - zip

packages_desktop:
  # list of basic desktop packages (installed with recommended packages)
  - alsa-base
  - alsa-utils
  - aptitude
  - ca-certificates
  - catfish
  - desktop-file-utils
  - dbus-x11
  - dmz-cursor-theme
  - doc-base
  - file-roller
  - fonts-dejavu
  - fonts-liberation
  - fonts-opensymbol
  - fonts-ubuntu
  - ghostscript-x
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-base-apps
  - gstreamer1.0-plugins-good
  - gstreamer1.0-pulseaudio
  - gstreamer1.0-tools
  - gtk2-engines
  - gtk2-engines-pixbuf
  - gvfs
  - gvfs-backends
  - gvfs-fuse
  - ibus
  - ibus-gtk
  - ibus-pinyin
  - ibus-table
  - im-switch
  - indicator-application
  - indicator-sound
  - inputattach
  - laptop-detect
  - libasound2-plugins
  - libnotify-bin
  - libpam-gnome-keyring
  - libxfce4ui-utils
  - lightdm
  - lightdm-gtk-greeter
  - lightdm-gtk-greeter-settings
  - pavucontrol
  - pcmciautils
  - policykit-desktop-privileges
  - thunar
  - thunar-volman
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - tumbler
  - wireless-tools
  - wpasupplicant
  - xcursor-themes
  - xdg-user-dirs
  - xdg-user-dirs-gtk
  - xdg-utils
  - xfce4-appfinder
  - xfce4-datetime-plugin
  - xfce4-indicator-plugin
  - xfce4-notifyd
  - xfce4-panel
  - xfce4-power-manager
  - xfce4-screenshooter
  - xfce4-session
  - xfce4-settings
  - xfce4-taskmanager
  - xfce4-terminal
  - xfce4-xkb-plugin
  - xfdesktop4
  - xfwm4
  - xkb-data
  - xorg
  - xterm
  - xubuntu-artwork
  - xubuntu-default-settings
  - ubuntu-drivers-common
  - xul-ext-ubufox
  - zenity


packages_office:
  # list of default office packages (installed without recommended packages)
  - conky-std
  - cups
  - cups-bsd
  - cups-client
  - cups-filters
  - evince
  - firefox
  - foomatic-db-compressed-ppds
  - foomatic-db-engine
  - freerdp2-x11
  - libfreerdp-client2-2
  - gnome-calculator
  - gdisk
  - geany
  - gimp
  - gthumb
  - recordmydesktop
  - htop
  - hplip
  - imagemagick
  - inkscape
  - mousepad
  - keepassx
  - libreoffice
  - libreoffice-calc
  - libreoffice-gtk3
  - libreoffice-writer
  - mc
  - mutt
  - openprinting-ppds
  - pidgin
  - printer-driver-c2esp
  - printer-driver-foo2zjs
  - printer-driver-gutenprint
  - printer-driver-hpcups
  - printer-driver-hpijs
  - printer-driver-min12xxw
  - printer-driver-pnm2ppa
  - printer-driver-postscript-hp
  - printer-driver-ptouch
  - printer-driver-pxljr
  - printer-driver-sag-gdi
  - printer-driver-splix
  - pssh
  - rst2pdf
  - system-config-printer
  - sshfs
  - vim-gtk3
  - vlc
  - x11vnc
  - xtightvncviewer


packages_lab:
  # list of GIS.lab client GIS packages (installed without recommended packages)
  - eodag
  - gdal-bin
  - git
  - grass
  - grass-doc
  - grass-dev
  - ipython3
  - monteverdi
  - osm2pgrouting
  - osm2pgsql
  - otb-bin
  - otb-bin-qt
  - otb-qgis
  - phppgadmin
  - postgis
  - postgis-doc
  - postgresql-client
  - postgresql-comparator
  - proj-bin
  - python3-fiona
  - python3-gdal
  - python3-owslib
  - python3-pandas
  - python3-geopandas
  - python3-pil
  - python3-pip
  - python3-pyproj
  - python3-qgis
  - python3-rasterio
  - python3-saga
  - python3-setuptools
  - python3-shapely
  - python3-sklearn
  - pyqt5-dev-tools
  - qgis
  - qgis-plugin-grass
  - qgit
  - saga
  - spatialite-bin
  - spatialite-gui
  - sqlite3
  - sqlitebrowser
  - josm

packages_lab_pip:
  # list of GIS.lab client GIS PIP packages
  - pymodis

packages_worker:
  # OWS worker packages
  - lighttpd
  - python3-gdal
  - python3-qgis
  - qgis
  - qgis-server
  - xvfb


packages_remove:
  # List of packages which have been installed automatically as dependency but
  # we don't want them to be installed. Run  '$ aptitude why <package>' find out
  # the reason why package was installed.
  - network-manager
  - network-manager-pptp
  - netplan.io
  - resolvconf
  - xscreensaver

nvidia_driver_version: 550

pycharm_version: 2024.3.1.1

# -o Dpkg::Options::="--force-confold" ???
apt_get_opts: "--assume-yes --force-yes"

# vim: set ts=8 sts=2 sw=2 et:
