---
#
### Build GIS.lab Desktop client image for LAN
#

- name: Install packages (default provider)
  apt:
    name: squashfs-tools
    force: yes
    install_recommends: no
    state: latest


### IMAGE
- name: Build GIS.lab client image
  shell: gislab-client-image > /dev/null
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ GISLAB_PATH_ADMIN }}:{{ ansible_env.PATH }}"

- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
