---
#
###  BUILD DOCUMENTATION ###
#
# Download documentation, build HTML output and link to default web page content.
#

- name: Install packages
  apt:
    name:
      - make
      - python3-sphinx
      - python3-sphinx-rtd-theme
    force: yes
    install_recommends: no
    state: latest

- name: Install Python packages
  pip:
    name:
      - sphinxcontrib-images
    break_system_packages: yes

- name: Download GIS.lab documentation
  git:
    repo: https://github.com/gislab-npo/gislab-doc.git
    dest: "{{ docs_dir }}"

- name: Build HTML documentation output
  shell: make html
  args:
    chdir: "{{ docs_dir }}"


- name: Create docs directory in default web content
  file:
    path: "{{ GISLAB_PATH_WWW }}/docs"
    state: directory
    mode: 0755

- name: Add GIS.lab documentation to default web content
  file:
    src: "{{ docs_dir }}/_build/html"
    dest: "{{ GISLAB_PATH_WWW }}/docs/gislab"
    state: link

# vim: set ts=8 sts=2 sw=2 et:
