---

- name: service named stop
  service:
    name: named
    enabled: no
    state: stopped

- name: service systemd-resolved restart
  service:
    name: systemd-resolved.service
    state: restarted
    enabled: yes

# vim: set ts=8 sts=2 sw=2 et:
